services:
  php_fpm:
    build: 
       context: app
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - my-sql-db

  my-sql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bookapp
    volumes:
      - my-db-vol:/var/lib/mysql

  httpd:
    build:
      context: httpd
    ports:
      - 80:80
    restart: always
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./db.php:/var/www/html/db.php
      - ./books.php:/var/www/html/books.php
      - ./views:/var/www/html/views  
    depends_on:
      - php_fpm
volumes:
  my-db-vol:  
