apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: vishnusatheesan/kubernetes:php_fpm_httpd-0.2
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-host

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-name

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-user

          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-password 
        
        volumeMounts:  
        - name: host-file-source
          mountPath: /var/www/html/index.php
          subPath: index.php
        - name: host-file-source
          mountPath: /var/www/html/db.php
          subPath: db.php
        - name: host-file-source
          mountPath: /var/www/html/books.php
          subPath: books.php
        - name: host-file-source
          mountPath: /var/www/html/views
          subPath: views    
      volumes: 
      - name: host-file-source
        hostPath: 
          path: /data/php-app
          type: DirectoryOrCreate        

